import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { motion } from 'framer-motion'
import Navbar from '../components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const StyleContainer ={
    hidden:{
      opacity:0
  },
  visible:{
      opacity:1,
      transition:{
          staggerChildren:0.5,
          when:"beforeChildren",
          delay:1
      }
  }
  }

  const heading = {
    hidden:{
      x:"100vw"
    
    },
    visible:{
      x:0,
      transition:{
        duration:0.6
      }
    }
  }
    const btn ={
      hidden:{
        y:"100vw"
      },
      visible:{
        y:0,
        transition:{
          duration:0.6,
          delay:0.7
        }
      }
    }
    const shoes = [
      {
          img:"/air-vapormax-2021-fk-mens-shoes-NpTfFzqq.png",
          title:"NIKE AIR VAPOMAX 2022 FK",
          price:"$130",
          icon:"/Group 2.png"
      },
      {
        img:"/air-zoom-pegasus-38-womens-road-running-shoes-gg8GBK11.png",
        title:"NIKE AIR VAPOMAX 2022 FK",
        price:"$180",
        icon:"/Group 2.png"
    },
    {
      img:"/blazer-low-77-big-kids-shoes-n2Bf0Leeeee.png",
      title:"NIKE AIR VAPOMAX 2022 FK",
      price:"$230",
      icon:"/Group 2.png"
  }
    ]
  
  return (
    <>
      <Head>
        <title>GREEN LEG</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/usama-akram-kP6knT7tjn4-unsplash 2.png" />
      </Head>

      <Navbar/>

<div className="flex justify-center items-center -ml-[80px] ">
      <div className="flex justify-center items-center">
      <motion.div initial={{opacity:0, x:-300}} animate={{opacity:1,x:0,rotate:0}} transition={{duration:0.6}} className="">
         
         <Image
           src="/usama-akram-kP6knT7tjn4-unsplash 2.png"
           alt="Vercel Logo"
           className='z-5'
         
           width={800}
           height={500}
           priority
         />
    
   </motion.div>

   <motion.div className='-mt-[150px] -ml-[358px]' variants={StyleContainer} initial="hidden" animate="visible" >
    <motion.h1 className="text-7xl font-bold z-2" variants={heading}>STYLES FOR <br/>SELF LOVE</motion.h1>
    <motion.div className='mt-[20px] ml-[160px]' variants={btn}>
      <button className='bg-[#75A204] w-[220px] p-3 text-black font-bold shadow-lg flex items-center justify-center gap-2'>SHOP NOW<Image src="/Arrow 2.png"width={30} height={20} alt="arrow"/></button>
    </motion.div>

   </motion.div>

      </div>
    
       

      </div>

      <div className='p-3 bg-[#B3E140] h-[500px] ' style={{borderTopLeftRadius:'300px'}} >
        <h1 className='text-7xl text-right opacity-[0.5] font-bold mb-[0px] mr-[30px]'>POPULAR</h1>
        <h1 className='text-4xl text-right  font-bold mb-[10px] -mt-[30px]  mr-[30px]'>RIGHT NOW</h1>

        <div className='flex gap-[40px] justify-center items-center '>
          {
            shoes.map((item)=>{
              return(
                <div className='bg-[#C3EB5F] h-[300px] w-[270px] flex flex-col justify-center items-center p-2 relative' style={{borderTopLeftRadius:'100px'}}>
                  <div className="absolute left-[50px] top-[30px]">  <Image src="/luv.png" width={30} height={30} alt="shoe"/></div>
                  <Image src={item.img} width={250} height={100} alt="shoe"/>
                  <div className='flex justify-between absolute items-center -bottom-[80px] p-4'>
                   <p className='text-2xl font-bold'>{item.title}</p>
                   <p className='text-2xl font-bold flex flex-col items-center justify-center'>{item.price}<br/>
                   <Image src={item.icon} width={50} height={50} alt="icon"/></p>
                  </div>
                </div>
              )
            })
          }
        </div>

      </div>
      <div className='p-3 bg-[#B3E140]  flex items-center justify-center' >
        <div>
          <h2 className='text-9xl font-bold'>JUST.</h2>
          <h2 className='text-9xl font-bold'>DO.</h2>
          <h2 className='text-9xl font-bold'>IT.</h2>
        </div>
        <motion.div initial={{opacity:0,x:200}} animate={{opacity:1,x:0}}>
        <Image src="/manrun.png" width={500} height={50} alt="icon"/>
        </motion.div>

    
      </div>
         
    </>
  )
}
